server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: -1

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  web:
    resources:
      static-locations: classpath:/build/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: truetech
        loginPassword: truetech
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      primary: sys
      druid: # 全局druid参数，单独数据源配置为空时取全局配置
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 10
        min-idle: 10
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
mybatis:
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

fast-common:
  # 文件路径 示例（ Windows配置D:/fastcommon/uploadPath，Linux配置 /home/fastcommon/uploadPath）
  profile: D:/fastcommon/uploadPath
  #  用户地址获取功能是否开启
  login-address-switch: true
  # 用户配置
  user:
    password:
      # 密码最大错误次数
      maxRetryCount: 5
      # 密码锁定时间（默认10分钟）
      lockTime: 10
  # token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
